## Pandas in python

In [86]:
# pandas series
import numpy as np
import pandas as pd

dt = np.array(['a','e','e','f','s','l'])
ser = pd.Series(dt)
print("series is:")
print(ser)

series is:
0    a
1    e
2    e
3    f
4    s
5    l
dtype: str

In [87]:
# pandas dataframe
import pandas as pd

df = pd.DataFrame()
print(df)

li = ["apple","banana","mango","kiwi","orange"]
df = pd.DataFrame(li)
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   apple
1  banana
2   mango
3    kiwi
4  orange

In [88]:
import pandas as pd
df = pd.read_csv("one.csv")
print(df)

   rno name   age      city  salary  bonus  total
0    1  jay  21.0     surat   10000   1000    NaN
1    2  man  23.0    amreli   11000   1000    NaN
2    3  dip  22.0    rajkot   10000   1000    NaN
3    4  raj   NaN  junagadh   13000   1000    NaN
4    5  ram  26.0       NaN   10000   1000    NaN

In [89]:
import pandas as pd
df = pd.read_csv("one.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rno     5 non-null      int64
 1   name    5 non-null      str
 2   age     4 non-null      float64
 3   city    4 non-null      str
 4   salary  5 non-null      int64
 5   bonus   5 non-null      int64
 6   total   0 non-null      float64
dtypes: float64(2), int64(3), str(2)
memory usage: 412.0 bytes

In [90]:
import pandas as pd
df = pd.read_csv("one.csv")
print(df.isnull())

     rno   name    age   city  salary  bonus  total
0  False  False  False  False   False  False   True
1  False  False  False  False   False  False   True
2  False  False  False  False   False  False   True
3  False  False   True  False   False  False   True
4  False  False  False   True   False  False   True

In [91]:
import pandas as pd
df = pd.read_csv("one.csv")
print(df.notnull())

    rno  name    age   city  salary  bonus  total
0  True  True   True   True    True   True  False
1  True  True   True   True    True   True  False
2  True  True   True   True    True   True  False
3  True  True  False   True    True   True  False
4  True  True   True  False    True   True  False

In [92]:
import pandas as pd
df = pd.read_csv("one.csv")
print(df.fillna(0))

   rno name   age      city  salary  bonus  total
0    1  jay  21.0     surat   10000   1000    0.0
1    2  man  23.0    amreli   11000   1000    0.0
2    3  dip  22.0    rajkot   10000   1000    0.0
3    4  raj   0.0  junagadh   13000   1000    0.0
4    5  ram  26.0         0   10000   1000    0.0

In [93]:
import pandas as pd
df = pd.read_csv("one.csv")
df.dropna()         # remove blank value row

Empty DataFrame
Columns: [rno, name, age, city, salary, bonus, total]
Index: []

In [94]:
import pandas as pd
df = pd.read_csv("one.csv")
age = df[df["age"] <= 22]
print(age)

   rno name   age    city  salary  bonus  total
0    1  jay  21.0   surat   10000   1000    NaN
2    3  dip  22.0  rajkot   10000   1000    NaN

In [95]:
import pandas as pd
df = pd.read_csv("one.csv")
df["total"] = df["salary"] + df["bonus"]
print(df)

   rno name   age      city  salary  bonus  total
0    1  jay  21.0     surat   10000   1000  11000
1    2  man  23.0    amreli   11000   1000  12000
2    3  dip  22.0    rajkot   10000   1000  11000
3    4  raj   NaN  junagadh   13000   1000  14000
4    5  ram  26.0       NaN   10000   1000  11000

In [ ]:
import pandas as pd
df = pd.read_csv('one.csv')
result = df.groupby("salary").groups
print(result)

{10000: [0, 2, 4], 11000: [1], 13000: [3]}

In [109]:
import pandas as pd
df = pd.read_csv('one.csv')       # sorting()
df.groupby("name").sum()

      rno   age      city  salary  bonus  total
name
dip     3  22.0    rajkot   10000   1000    0.0
jay     1  21.0     surat   10000   1000    0.0
man     2  23.0    amreli   11000   1000    0.0
raj     4   0.0  junagadh   13000   1000    0.0
ram     5  26.0             10000   1000    0.0

In [107]:
import pandas as pd
df = pd.read_csv('one.csv')
grp = df.groupby("name")
grp.get_group("jay")

   rno name   age   city  salary  bonus  total
0    1  jay  21.0  surat   10000   1000    NaN

In [ ]:
import pandas as pd
df = pd.read_csv("one.csv")
df.head(2)      # two row display

   rno name   age    city  salary  bonus  total
0    1  jay  21.0   surat   10000   1000    NaN
1    2  man  23.0  amreli   11000   1000    NaN

In [ ]:
import pandas as pd
df = pd.read_csv("one.csv")
df.head()      # first five row display

   rno name   age      city  salary  bonus  total
0    1  jay  21.0     surat   10000   1000    NaN
1    2  man  23.0    amreli   11000   1000    NaN
2    3  dip  22.0    rajkot   10000   1000    NaN
3    4  raj   NaN  junagadh   13000   1000    NaN
4    5  ram  26.0       NaN   10000   1000    NaN

In [124]:
import pandas as pd
df = pd.read_csv("one.csv")
df.tail(2)      # last two row display

   rno name   age      city  salary  bonus  total
3    4  raj   NaN  junagadh   13000   1000    NaN
4    5  ram  26.0       NaN   10000   1000    NaN

In [110]:
import pandas as pd 
df = pd.read_json("one.json")
print(df)

  name  age          email  married children               address
0  jay   21  jay@gmail.com     True    mayur  {'city': 'bagasara'}
1  jay   21  jay@gmail.com     True   mayuri   {'pincode': 365440}

In [111]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300